### ISSUE TITLE
US 01.01.01

### ISSUE THREAD

**Issue by Koss24** [CMPUT301F23T22/Hoard_And_Store#7]
As an owner, I want to add an item to my items, with a date of purchase or acquisition, brief description, make, model, serial number (if applicable), estimated value, and comment.

Acceptance Criteria
- [x] Button on home page to go to add expense view
- [x] Simple way to add
- [x] Validate info is correct

SP: 3

**Comment by paudeldeepak** [comment]
@jugalp10 @PhamNamSon still need to a thing where in the text field it says bad input
